name: amiriy
description: "Amiriy kutubxonasi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  http: ^1.2.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.0
  cached_network_image: ^3.3.1
  zoom_tap_animation: ^1.1.0
  lottie: ^3.1.0
  flutter_local_notifications: ^17.0.0
  flutter_timezone: ^3.0.1
  change_app_package_name: ^1.1.0
  firebase_messaging: ^15.1.0
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  firebase_storage: ^12.2.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  mask_text_input_formatter: ^2.9.0
  easy_localization: ^3.0.6
  shimmer: ^3.0.0
  adaptive_theme: ^3.6.0
  connectivity_plus: ^6.0.3
  fluttertoast: ^8.2.5
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.6.1
  location: ^7.0.0
  url_launcher: ^6.2.6
  just_audio: ^0.9.18
  audio_service: ^0.18.0
  rxdart: ^0.28.0
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^6.1.0
  on_audio_query: ^2.9.0

  my_utils:
    path: packages/my_utils
  flutter_cached_pdfview: ^0.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/bodoni/
    - assets/fonts/inter/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/

  fonts:
    - family: Bodoni
      fonts:
        - asset: assets/fonts/bodoni/BodoniFLF-Bold.ttf
        - asset: assets/fonts/bodoni/BodoniFLF-BoldItalic.ttf
        - asset: assets/fonts/bodoni/BodoniFLF-Italic.ttf
          style: italic
        - asset: assets/fonts/bodoni/BodoniFLF-Roman.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
        - asset: assets/fonts/inter/Inter-Italic.otf
        - asset: assets/fonts/inter/Inter-Light.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-SemiBold.otf