// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkt6Y0zXTaopOwSmZE64ZCkfv9akwQmDg',
    appId: '1:762812355330:android:d51d9281042d38054fe81b',
    messagingSenderId: '762812355330',
    projectId: 'e-commerce-app-863de',
    databaseURL: 'https://e-commerce-app-863de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-863de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy5HLgpP7F55JzY0NzbmWMYNkrOPBmV2E',
    appId: '1:762812355330:ios:022a6475826eea724fe81b',
    messagingSenderId: '762812355330',
    projectId: 'e-commerce-app-863de',
    databaseURL: 'https://e-commerce-app-863de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-863de.appspot.com',
    androidClientId: '762812355330-14k24rndh7986g5onnoq8ie11278nmup.apps.googleusercontent.com',
    iosBundleId: 'com.example.amiriy',
  );
}
